"""SQLAlchemy ORM models — backward-compatible re-exports."""

from src.db.models._base import Base, User
from src.db.models._auth import (
    UserSettings,
    TelegramSession,
    ApiKey,
    LlmKeySlot,
    LlmKeySlotModel,
    PendingQuestion,
)
from src.db.models._contacts import (
    AllowedContact,
    Contact,
    ContactProfile,
    ConversationState,
)
from src.db.models._messaging import (
    Message,
    AutoReplyLog,
    TranscriptionCache,
    PendingAction,
    Notification,
    NewsTopic,
    Commitment,
    IndexJob,
    Folder,
    ConversationSummary,
    ScheduledMessage,
    MessageReaction,
    HumanizerFeedback,
)
from src.db.models._memory import (
    Entity,
    EntityRelation,
    Episode,
    EpisodeContact,
    Memory,
    MemoryLink,
    MemoryCluster,
    MemoryClusterMember,
    MemoryCandidate,
    MemoryVersion,
    WorkingMemory,
)
from src.db.models._cron import CronJob
from src.db.models._cache import SmartCacheEntry
from src.db.models._avito import AvitoListing, AvitoPriceHistory, AvitoWatch
from src.db.models._monitor import (
    MonitoredSource,
    MonitorRule,
    MonitoredMessage,
    MonitoredAlert,
)
from src.db.models._learning import (
    AgentCache,
    SelfProfile,
    AdaptivePersona,
    SoulSnapshot,
    Trajectory,
    Skill,
    SkillUsage,
    InstructionProfile,
    InstructionCandidate,
    InstructionEvent,
)
from src.db.models._session import (
    AgentSession,
    AgentSessionMessage,
    SessionContext,
)
from src.db.models._encryption import EncryptionKey
from src.db.models._research import ResearchJob
from src.db.models._timer import Timer

__all__ = [
    "AdaptivePersona",
    "AgentCache",
    "AgentSession",
    "AgentSessionMessage",
    "AllowedContact",
    "ApiKey",
    "AutoReplyLog",
    "AvitoListing",
    "AvitoPriceHistory",
    "AvitoWatch",
    "Base",
    "Commitment",
    "Contact",
    "ContactProfile",
    "ConversationState",
    "ConversationSummary",
    "CronJob",
    "EncryptionKey",
    "Entity",
    "EntityRelation",
    "Episode",
    "EpisodeContact",
    "Folder",
    "HumanizerFeedback",
    "IndexJob",
    "InstructionCandidate",
    "InstructionEvent",
    "InstructionProfile",
    "LlmKeySlot",
    "LlmKeySlotModel",
    "Memory",
    "MemoryCandidate",
    "MemoryCluster",
    "MemoryClusterMember",
    "MemoryLink",
    "MemoryVersion",
    "Message",
    "MessageReaction",
    "MonitorRule",
    "MonitoredAlert",
    "MonitoredMessage",
    "MonitoredSource",
    "NewsTopic",
    "Notification",
    "PendingAction",
    "PendingQuestion",
    "ResearchJob",
    "ScheduledMessage",
    "SelfProfile",
    "SessionContext",
    "Skill",
    "SkillUsage",
    "SmartCacheEntry",
    "SoulSnapshot",
    "TelegramSession",
    "Timer",
    "Trajectory",
    "TranscriptionCache",
    "User",
    "UserSettings",
    "WorkingMemory",
]
