"""add_scheduling_persist_columns

Revision ID: 318404aba419
Revises: 0ea3133e3615
Create Date: 2026-05-22 11:15:59.292489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '318404aba419'
down_revision: Union[str, Sequence[str], None] = '0ea3133e3615'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commitments', sa.Column('last_reminded_at', sa.DateTime(), nullable=True))
    op.add_column('user_settings', sa.Column('proactive_last_sent', sa.DateTime(), nullable=True))
    op.add_column('user_settings', sa.Column('habit_last_run_date', sa.Date(), nullable=True))
    op.alter_column('user_settings', 'llm_provider',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=24),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_settings', 'llm_provider',
               existing_type=sa.String(length=24),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)
    op.drop_column('user_settings', 'habit_last_run_date')
    op.drop_column('user_settings', 'proactive_last_sent')
    op.drop_column('commitments', 'last_reminded_at')
    # ### end Alembic commands ###
