"""Canonical relation type constants for MemoryLink.

All relation type strings used across the memory subsystem are defined here
as a ``str, Enum`` to prevent typos (e.g. ``"supersede"`` instead of
``"supersedes"``) that would silently break link matching and chain traversal.

Usage::

    from src.core.memory.relation_types import RelationType

    RelationType.SUPERSEDES          # "supersedes"
    RelationType.SUPERSEDES == "supersedes"   # True (str subtype)
    RelationType.SUPERSEDES in some_dict      # True (same hash as str)

The values are identical to the database strings in ``memory_links.relation_type``,
so no migration is needed.
"""

from __future__ import annotations

from enum import Enum


class RelationType(str, Enum):
    """MemoryLink relation types — LLM-extractable AND programmatic.

    All members are str subtypes. They can be used anywhere a plain string
    is expected: database queries, dict lookups, JSON serialization, etc.

    LLM-extractable types (appear in ``memory_extractor.MEMORIES_SYSTEM`` prompt):
    """

    # ── LLM-extractable ──────────────────────────────────────────────────

    CAUSE = "cause"
    """A is the cause of B. Causal relationship (A → B)."""

    EFFECT = "effect"
    """A is the effect/consequence of B (B → A)."""

    CONTRADICTS = "contradicts"
    """A contradicts B. The facts are in logical conflict."""

    SUPPORTS = "supports"
    """A supports/confirms B. Reinforcing or corroborating relationship."""

    CONTINUES = "continues"
    """A continues the topic/thread of B. Thematic continuation."""

    EXAMPLE_OF = "example_of"
    """A is an example/instance of B. Exemplification."""

    SUPERSEDES = "supersedes"
    """A supersedes B. A is a newer, more accurate, or updated version of B.

    Used by ``follow_supersedes_chain`` to build evolution chains
    showing how facts change over time.
    """

    # ── Programmatic-only (auto-generated, never from LLM) ───────────────

    CO_TEMPORAL = "co_temporal"
    """A and B occurred close in time (same contact, <1 hour apart).

    Auto-generated by ``_auto_link_memory`` temporal pass."""

    CO_ENTITY = "co_entity"
    """A and B share the same proper nouns (named entities).

    Auto-generated by ``_auto_link_memory`` entity pass."""

    PRECEDED = "preceded"
    """A preceded B in time. Temporal ordering hint.

    Auto-generated when a new negative-fact follows positive facts
    of the same contact (cause-effect heuristic)."""

    RELATED = "related"
    """A and B are related (keyword overlap or moderate vector similarity).

    Auto-generated by ``_auto_link_memory`` as a fallback or weak link.
    Not in the LLM-validation whitelist because it is never LLM-generated."""


# ── Backward-compatible frozenset for LLM validation ──────────────────────
# Used by link_memories() to reject hallucinated relation types from LLMs
# (e.g. "supersede", "replaces").  Does NOT include "related" because
# LLMs never produce it — it is purely programmatic.
_VALID_FOR_LLM: frozenset[str] = frozenset(
    {
        RelationType.CAUSE,
        RelationType.EFFECT,
        RelationType.CONTRADICTS,
        RelationType.SUPPORTS,
        RelationType.CONTINUES,
        RelationType.EXAMPLE_OF,
        RelationType.SUPERSEDES,
        RelationType.CO_TEMPORAL,
        RelationType.CO_ENTITY,
        RelationType.PRECEDED,
    }
)

# ── All relation types as plain strings (convenience) ────────────────────
ALL_VALUES: list[str] = [r.value for r in RelationType]
